### ISSUE TITLE
Fail to transition on heartbeat

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/atomix#118] opened 2019-12-02 16:39 UTC
**Expected behavior**

In `ActiveRole#onLeaderHeartbeat:250`, we transition to follower role; I expect this to succeed.

**Actual behavior**

When we transition, we transition from the heart beat thread, but the transition method expects this call to come from the Raft thread and throws an exception. We should fix the cross-thread issue.

**Comment by ChrisKujawa** [comment] 2019-12-03 06:18
duplicate of https://github.com/zeebe-io/atomix/issues/64

**Closed as completed by ChrisKujawa** 2019-12-03 06:18 UTC
Labels: bug
